// Auto generated by utensor-cli

#include "uTensor/core/tensor.hpp"
#include "uTensor/ops/MatrixOps.hpp"
#include "trained.hpp"
#include "uTensor/ops/ArrayOps.hpp"
#include "uTensor/ops/MathOps.hpp"
#include "trained_weight.hpp"
#include "uTensor/ops/NnOps.hpp"
#include "uTensor/core/context.hpp"


void get_trained_ctx(Context& ctx, Tensor* input_0) {

{ // add tensor for placeholders
    ctx.add(input_0, "x_input:0", 2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_1_MatMul_eightbit_x_input__port__0_reshape_dims_0), 
            "dense_1/MatMul_eightbit/x_input__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "dense_1/MatMul_eightbit/x_input__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "x_input:0", "dense_1/MatMul_eightbit/x_input__port__0/reshape_dims:0" },
             { "dense_1/MatMul_eightbit/x_input__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_1_MatMul_eightbit_x_input__port__0_reduction_dims_0), 
            "dense_1/MatMul_eightbit/x_input__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_1/MatMul_eightbit/x_input__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "dense_1/MatMul_eightbit/x_input__port__0/reshape:0", "dense_1/MatMul_eightbit/x_input__port__0/reduction_dims:0" },
             { "dense_1/MatMul_eightbit/x_input__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_1/MatMul_eightbit/x_input__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "dense_1/MatMul_eightbit/x_input__port__0/reshape:0", "dense_1/MatMul_eightbit/x_input__port__0/reduction_dims:0" },
             { "dense_1/MatMul_eightbit/x_input__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_1/MatMul_eightbit/x_input__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1/MatMul_eightbit/x_input__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1/MatMul_eightbit/x_input__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "x_input:0",  "dense_1/MatMul_eightbit/x_input__port__0/min:0", "dense_1/MatMul_eightbit/x_input__port__0/max:0" },
             {  "dense_1/MatMul_eightbit/x_input__port__0/quantize:0",  "dense_1/MatMul_eightbit/x_input__port__0/quantize:1", "dense_1/MatMul_eightbit/x_input__port__0/quantize:2" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<float>({33,20}, inline_dense_1_kernel_0), 
            "dense_1/kernel:0", 
            2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_1_MatMul_eightbit_dense_1_kernel_read__port__0_reshape_dims_0), 
            "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "dense_1/kernel:0", "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/reshape_dims:0" },
             { "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_1_MatMul_eightbit_dense_1_kernel_read__port__0_reduction_dims_0), 
            "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/reshape:0", "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/reduction_dims:0" },
             { "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/reshape:0", "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/reduction_dims:0" },
             { "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "dense_1/kernel:0",  "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/min:0", "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/max:0" },
             {  "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/quantize:0",  "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/quantize:1", "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "dense_1/MatMul/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "dense_1/MatMul/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "dense_1/MatMul/eightbit:2", 2);
    ctx.push(new QntMatMulOp<uint8_t, uint8_t, int>(), 
             { "dense_1/MatMul_eightbit/x_input__port__0/quantize:0", "dense_1/MatMul_eightbit/x_input__port__0/quantize:1", "dense_1/MatMul_eightbit/x_input__port__0/quantize:2", "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/quantize:0", "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/quantize:1",  "dense_1/MatMul_eightbit/dense_1/kernel/read__port__0/quantize:2" },
             { "dense_1/MatMul/eightbit:0", "dense_1/MatMul/eightbit:1",  "dense_1/MatMul/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "dense_1/MatMul/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1/MatMul/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "dense_1/MatMul/eightbit:0", "dense_1/MatMul/eightbit:1", "dense_1/MatMul/eightbit:2" },
             { "dense_1/MatMul/eightbit/requant_range:0", "dense_1/MatMul/eightbit/requant_range:1" });
    ctx.eval();
}
{   
    ctx.add(new RamTensor<uint8_t>(), "dense_1/MatMul/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1/MatMul/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1/MatMul/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "dense_1/MatMul/eightbit:0", "dense_1/MatMul/eightbit:1", "dense_1/MatMul/eightbit:2", "dense_1/MatMul/eightbit/requant_range:0", "dense_1/MatMul/eightbit/requant_range:1" },
             { "dense_1/MatMul/eightbit/requantize:0", "dense_1/MatMul/eightbit/requantize:1", "dense_1/MatMul/eightbit/requantize:2" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<float>({20}, inline_dense_1_bias_0), 
            "dense_1/bias:0", 
            2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_1_BiasAdd_eightbit_dense_1_bias_read__port__0_reshape_dims_0), 
            "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "dense_1/bias:0", "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/reshape_dims:0" },
             { "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_1_BiasAdd_eightbit_dense_1_bias_read__port__0_reduction_dims_0), 
            "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/reshape:0", "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/reduction_dims:0" },
             { "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/reshape:0", "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/reduction_dims:0" },
             { "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "dense_1/bias:0",  "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/min:0", "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/max:0" },
             {  "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/quantize:0",  "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/quantize:1", "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "dense_1/BiasAdd/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "dense_1/BiasAdd/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "dense_1/BiasAdd/eightbit:2", 2);
    ctx.push(new QuantizedAddOp<uint8_t, uint8_t, int>(), 
             { "dense_1/MatMul/eightbit/requantize:0", "dense_1/MatMul/eightbit/requantize:1", "dense_1/MatMul/eightbit/requantize:2", "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/quantize:0", "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/quantize:1",  "dense_1/BiasAdd_eightbit/dense_1/bias/read__port__0/quantize:2" },
             { "dense_1/BiasAdd/eightbit:0", "dense_1/BiasAdd/eightbit:1",  "dense_1/BiasAdd/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "dense_1/BiasAdd/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1/BiasAdd/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "dense_1/BiasAdd/eightbit:0", "dense_1/BiasAdd/eightbit:1", "dense_1/BiasAdd/eightbit:2" },
             { "dense_1/BiasAdd/eightbit/requant_range:0", "dense_1/BiasAdd/eightbit/requant_range:1" });
    ctx.eval();
}
{   
    ctx.add(new RamTensor<uint8_t>(), "dense_1/BiasAdd/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1/BiasAdd/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1/BiasAdd/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "dense_1/BiasAdd/eightbit:0", "dense_1/BiasAdd/eightbit:1", "dense_1/BiasAdd/eightbit:2", "dense_1/BiasAdd/eightbit/requant_range:0", "dense_1/BiasAdd/eightbit/requant_range:1" },
             { "dense_1/BiasAdd/eightbit/requantize:0", "dense_1/BiasAdd/eightbit/requantize:1", "dense_1/BiasAdd/eightbit/requantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_1/Relu/eightbit:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1/Relu/eightbit:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_1/Relu/eightbit:2", 1);
    ctx.push(new QuantizedReluOp<uint8_t, float, uint8_t>(), 
             { "dense_1/BiasAdd/eightbit/requantize:0", "dense_1/BiasAdd/eightbit/requantize:1", "dense_1/BiasAdd/eightbit/requantize:2" },
             { "dense_1/Relu/eightbit:0", "dense_1/Relu/eightbit:1", "dense_1/Relu/eightbit:2" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<float>({20,10}, inline_dense_2_kernel_0), 
            "dense_2/kernel:0", 
            2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_2_MatMul_eightbit_dense_2_kernel_read__port__0_reshape_dims_0), 
            "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "dense_2/kernel:0", "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/reshape_dims:0" },
             { "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_2_MatMul_eightbit_dense_2_kernel_read__port__0_reduction_dims_0), 
            "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/reshape:0", "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/reduction_dims:0" },
             { "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/reshape:0", "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/reduction_dims:0" },
             { "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "dense_2/kernel:0",  "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/min:0", "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/max:0" },
             {  "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/quantize:0",  "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/quantize:1", "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "dense_2/MatMul/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "dense_2/MatMul/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "dense_2/MatMul/eightbit:2", 2);
    ctx.push(new QntMatMulOp<uint8_t, uint8_t, int>(), 
             { "dense_1/Relu/eightbit:0", "dense_1/Relu/eightbit:1", "dense_1/Relu/eightbit:2", "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/quantize:0", "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/quantize:1",  "dense_2/MatMul_eightbit/dense_2/kernel/read__port__0/quantize:2" },
             { "dense_2/MatMul/eightbit:0", "dense_2/MatMul/eightbit:1",  "dense_2/MatMul/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "dense_2/MatMul/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2/MatMul/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "dense_2/MatMul/eightbit:0", "dense_2/MatMul/eightbit:1", "dense_2/MatMul/eightbit:2" },
             { "dense_2/MatMul/eightbit/requant_range:0", "dense_2/MatMul/eightbit/requant_range:1" });
    ctx.eval();
}
{   
    ctx.add(new RamTensor<uint8_t>(), "dense_2/MatMul/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2/MatMul/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2/MatMul/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "dense_2/MatMul/eightbit:0", "dense_2/MatMul/eightbit:1", "dense_2/MatMul/eightbit:2", "dense_2/MatMul/eightbit/requant_range:0", "dense_2/MatMul/eightbit/requant_range:1" },
             { "dense_2/MatMul/eightbit/requantize:0", "dense_2/MatMul/eightbit/requantize:1", "dense_2/MatMul/eightbit/requantize:2" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<float>({10}, inline_dense_2_bias_0), 
            "dense_2/bias:0", 
            2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_2_BiasAdd_eightbit_dense_2_bias_read__port__0_reshape_dims_0), 
            "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "dense_2/bias:0", "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/reshape_dims:0" },
             { "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_dense_2_BiasAdd_eightbit_dense_2_bias_read__port__0_reduction_dims_0), 
            "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/reshape:0", "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/reduction_dims:0" },
             { "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/reshape:0", "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/reduction_dims:0" },
             { "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "dense_2/bias:0",  "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/min:0", "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/max:0" },
             {  "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/quantize:0",  "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/quantize:1", "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "dense_2/BiasAdd/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "dense_2/BiasAdd/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "dense_2/BiasAdd/eightbit:2", 2);
    ctx.push(new QuantizedAddOp<uint8_t, uint8_t, int>(), 
             { "dense_2/MatMul/eightbit/requantize:0", "dense_2/MatMul/eightbit/requantize:1", "dense_2/MatMul/eightbit/requantize:2", "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/quantize:0", "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/quantize:1",  "dense_2/BiasAdd_eightbit/dense_2/bias/read__port__0/quantize:2" },
             { "dense_2/BiasAdd/eightbit:0", "dense_2/BiasAdd/eightbit:1",  "dense_2/BiasAdd/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "dense_2/BiasAdd/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2/BiasAdd/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "dense_2/BiasAdd/eightbit:0", "dense_2/BiasAdd/eightbit:1", "dense_2/BiasAdd/eightbit:2" },
             { "dense_2/BiasAdd/eightbit/requant_range:0", "dense_2/BiasAdd/eightbit/requant_range:1" });
    ctx.eval();
}
{   
    ctx.add(new RamTensor<uint8_t>(), "dense_2/BiasAdd/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2/BiasAdd/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2/BiasAdd/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "dense_2/BiasAdd/eightbit:0", "dense_2/BiasAdd/eightbit:1", "dense_2/BiasAdd/eightbit:2", "dense_2/BiasAdd/eightbit/requant_range:0", "dense_2/BiasAdd/eightbit/requant_range:1" },
             { "dense_2/BiasAdd/eightbit/requantize:0", "dense_2/BiasAdd/eightbit/requantize:1", "dense_2/BiasAdd/eightbit/requantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "dense_2/Relu/eightbit:0", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2/Relu/eightbit:1", 1);
    ctx.add(new RamTensor<float>({1}), "dense_2/Relu/eightbit:2", 1);
    ctx.push(new QuantizedReluOp<uint8_t, float, uint8_t>(), 
             { "dense_2/BiasAdd/eightbit/requantize:0", "dense_2/BiasAdd/eightbit/requantize:1", "dense_2/BiasAdd/eightbit/requantize:2" },
             { "dense_2/Relu/eightbit:0", "dense_2/Relu/eightbit:1", "dense_2/Relu/eightbit:2" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<float>({10,4}, inline_y_pred_kernel_0), 
            "y_pred/kernel:0", 
            2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_y_pred_MatMul_eightbit_y_pred_kernel_read__port__0_reshape_dims_0), 
            "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "y_pred/kernel:0", "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/reshape_dims:0" },
             { "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_y_pred_MatMul_eightbit_y_pred_kernel_read__port__0_reduction_dims_0), 
            "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/reshape:0", "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/reduction_dims:0" },
             { "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/reshape:0", "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/reduction_dims:0" },
             { "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "y_pred/kernel:0",  "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/min:0", "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/max:0" },
             {  "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/quantize:0",  "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/quantize:1", "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "y_pred/MatMul/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "y_pred/MatMul/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "y_pred/MatMul/eightbit:2", 2);
    ctx.push(new QntMatMulOp<uint8_t, uint8_t, int>(), 
             { "dense_2/Relu/eightbit:0", "dense_2/Relu/eightbit:1", "dense_2/Relu/eightbit:2", "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/quantize:0", "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/quantize:1",  "y_pred/MatMul_eightbit/y_pred/kernel/read__port__0/quantize:2" },
             { "y_pred/MatMul/eightbit:0", "y_pred/MatMul/eightbit:1",  "y_pred/MatMul/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "y_pred/MatMul/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "y_pred/MatMul/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "y_pred/MatMul/eightbit:0", "y_pred/MatMul/eightbit:1", "y_pred/MatMul/eightbit:2" },
             { "y_pred/MatMul/eightbit/requant_range:0", "y_pred/MatMul/eightbit/requant_range:1" });
    ctx.eval();
}
{   
    ctx.add(new RamTensor<uint8_t>(), "y_pred/MatMul/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "y_pred/MatMul/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "y_pred/MatMul/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "y_pred/MatMul/eightbit:0", "y_pred/MatMul/eightbit:1", "y_pred/MatMul/eightbit:2", "y_pred/MatMul/eightbit/requant_range:0", "y_pred/MatMul/eightbit/requant_range:1" },
             { "y_pred/MatMul/eightbit/requantize:0", "y_pred/MatMul/eightbit/requantize:1", "y_pred/MatMul/eightbit/requantize:2" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<float>({4}, inline_y_pred_bias_0), 
            "y_pred/bias:0", 
            2);
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_y_pred_BiasAdd_eightbit_y_pred_bias_read__port__0_reshape_dims_0), 
            "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/reshape_dims:0", 
            1);
}
{
    ctx.add(new RamTensor<float>(), "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/reshape:0", 2);
    ctx.push(new ReshapeOp(), 
             { "y_pred/bias:0", "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/reshape_dims:0" },
             { "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/reshape:0" });
    ctx.eval();
}
{    
    ctx.add(new BinaryTensor<int>({1}, inline_y_pred_BiasAdd_eightbit_y_pred_bias_read__port__0_reduction_dims_0), 
            "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/reduction_dims:0", 
            2);
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/min:0", 1);
    ctx.push(new MinOp(), 
             { "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/reshape:0", "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/reduction_dims:0" },
             { "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/min:0" });
    ctx.eval();
}
{   
    RamTensor<float>* out_tensor;
    out_tensor = new RamTensor<float>({ 1 });
    ctx.add(out_tensor, "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/max:0", 1);
    ctx.push(new MaxOp(), 
             { "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/reshape:0", "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/reduction_dims:0" },
             { "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/max:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<uint8_t>(), "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/quantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/quantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/quantize:2", 1);
    ctx.push(new QuantizeV2Op(),
             {  "y_pred/bias:0",  "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/min:0", "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/max:0" },
             {  "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/quantize:0",  "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/quantize:1", "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/quantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<int>(), "y_pred/BiasAdd/eightbit:0", 2);
    ctx.add(new RamTensor<float>({1}), "y_pred/BiasAdd/eightbit:1", 2);
    ctx.add(new RamTensor<float>({1}), "y_pred/BiasAdd/eightbit:2", 2);
    ctx.push(new QuantizedAddOp<uint8_t, uint8_t, int>(), 
             { "y_pred/MatMul/eightbit/requantize:0", "y_pred/MatMul/eightbit/requantize:1", "y_pred/MatMul/eightbit/requantize:2", "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/quantize:0", "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/quantize:1",  "y_pred/BiasAdd_eightbit/y_pred/bias/read__port__0/quantize:2" },
             { "y_pred/BiasAdd/eightbit:0", "y_pred/BiasAdd/eightbit:1",  "y_pred/BiasAdd/eightbit:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>({1}), "y_pred/BiasAdd/eightbit/requant_range:0", 1);
    ctx.add(new RamTensor<float>({1}), "y_pred/BiasAdd/eightbit/requant_range:1", 1);
    ctx.push(new Requantization_RangeOp(),
             { "y_pred/BiasAdd/eightbit:0", "y_pred/BiasAdd/eightbit:1", "y_pred/BiasAdd/eightbit:2" },
             { "y_pred/BiasAdd/eightbit/requant_range:0", "y_pred/BiasAdd/eightbit/requant_range:1" });
    ctx.eval();
}
{   
    ctx.add(new RamTensor<uint8_t>(), "y_pred/BiasAdd/eightbit/requantize:0", 1);
    ctx.add(new RamTensor<float>({1}), "y_pred/BiasAdd/eightbit/requantize:1", 1);
    ctx.add(new RamTensor<float>({1}), "y_pred/BiasAdd/eightbit/requantize:2", 1);
    ctx.push(new RequantizeOp(),
             { "y_pred/BiasAdd/eightbit:0", "y_pred/BiasAdd/eightbit:1", "y_pred/BiasAdd/eightbit:2", "y_pred/BiasAdd/eightbit/requant_range:0", "y_pred/BiasAdd/eightbit/requant_range:1" },
             { "y_pred/BiasAdd/eightbit/requantize:0", "y_pred/BiasAdd/eightbit/requantize:1", "y_pred/BiasAdd/eightbit/requantize:2" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>(), "y_pred/BiasAdd:0", 1);
    ctx.push(new DequantizeOp(), 
             { "y_pred/BiasAdd/eightbit/requantize:0", "y_pred/BiasAdd/eightbit/requantize:1", "y_pred/BiasAdd/eightbit/requantize:2" },
             { "y_pred/BiasAdd:0" });
    ctx.eval();
}
{
    ctx.add(new RamTensor<float>(), "y_pred/Softmax:0");
    ctx.push(new SoftmaxOp(),
             { "y_pred/BiasAdd:0" },
             { "y_pred/Softmax:0" });
}
}