// Auto generated by utensor-cli

#ifndef __FW_UTENSOR_MODEL_TRAINED_H
#define __FW_UTENSOR_MODEL_TRAINED_H
#include "uTensor/core/context.hpp"
void get_trained_ctx(Context& ctx, Tensor* input_0);
#endif // __FW_UTENSOR_MODEL_TRAINED_H